project:
  type: website
  render:
  - "*.qmd"
  - "*.ipynb"
  - "README.md"

execute:
  freeze: auto

website:
  navbar:
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/espm-288/cloud-native-geo-cboettig
          - text: Report a Bug
            url:  ttps://github.com/espm-288/cloud-native-geo-cboettig/issues
    background: black
    search: true
    left:
      - text: "Home"
        file: README.md 

  sidebar:
    contents: tutorials         
